concurrency:
    cancel-in-progress: false
    group: "pages"

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }/reactify
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "./dist"
            - id: deployment
              name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2

name: Deploy static content to Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pages: write
